[[_wifi_config]]
= WiFi configuration on ESP8266


When prototyping an idea with ESP8266, people usually focus on the features of that ideas, not the user's experience. So a fully-functioning prototype could lack of a user interface, a keyboard or a touchscreen,... That would lead to some inconveniences for users.


For example, whenever an ESP8266 wants to connect to a new WEP/WPA/WPA2 WiFi Access Point, we must manually provide the AP's configuration, SSID and password in the source code and compile those code into a new binary file on PC. Then using a USB cable, we upload that file to the device just to change the WiFi AP!


To deal with those problems, ESP8266 provides some user-friendly alternatives to simplify the WiFi set-up process. In this chapter, we are introducing `SmartConfig`, `WPS` and `WiFi Manager`.


include::01-smartconfig.{lang}.adoc[]

include::02-wps.{lang}.adoc[]

include::03-wifi-manager.{lang}.adoc[]

== Summary


When you build an IoT system in real life, you will face many challenges. One of the most important challenges is making your product easy-to-use, easy-to-configure and secure during data transmission. You should consider your purpose and your product's functionalities to choose an appropriate solution to configure WiFi connection.


For example, if your device contains buttons or a smartphone app, you should consider choosing SmartConfig or WPS. Or, if you are making a smart light bulb with the ability to control over WiFi, then WiFIManager will be the most suitable solution. It's up on you!
