== WiFi Station Mode

=== Knownledge

To connect to the Internet, ESP8266 needs to connect to a local WiFi network, and this network must connect to a Internet WAN. Most modems nowsaday have WiFi Access Point intergrated, which make it easy to deploy IoT application.

ESP8266 must be in Station (STA) mode to connect to a local WiFi network, and must be supplied with a SSID and a password.

Each Access Point implements a security protocol in connections with Stations, e.g. `WEP`, `WPA2`. Howver, this would not be an issue in development since ESP8266 has pre-configured the necessary protocol.

Upon successful connection to a network, ESP8266 automatically initialise a default DHCP Client, requesting for IP before accepting any IP connection. Thus, for some reason if a DHCP Server is not available, static IP must be manually configured for ESP8266.

=== Connecting to a local network

With the provied code, if a given `SSID` and `PASSWORD` are correct and an Access Point is up and running, the module will establish a connection and print out the Serial Terminal the provided local IP of ESP866 in the LAN network.

[source, c]
----
include::code-{lang}/WiFiClient/WiFiClient.ino[]
----

=== Using WiFiMulti

Nevertheless, as a precaution, having 2-3 WiFi network as backup is advisable, WiFiMulti class will prove useful. A simple monitoring function will notify other functions when a connection is made.

[source, c]
----
include::code-{lang}/WiFiMulti/WiFiMulti.ino[]
----

Proceed after checking the source code:

- <<select-arduino-board>>
- <<arduino-flash>>
