== Web Server

=== Web Server là gì?

Web Server là một máy chủ Web mà khi có bất kỳ một Web Client nào (chẳng hạn Web Browser) truy cập vào, thì nó sẽ căn cứ trên các thông tin yêu cầu truy cập để xử lý, và phản hồi lại nội dung. Đa phần các nội dung Web Server phục vụ là HTML, Javascript, CSS, JSON và bao gồm cả các dữ liệu Binary.

Mặc định các Web Server phục vụ trên Port 80, và 443 cho dịch vụ Web có bảo mật HTTPS

=== HTML - Javascript - CSS

HTML, Javascript và CSS là ba ngôn ngữ để xây dựng và phát triển Web. Những hiểu biết cơ bản về chúng sẽ tạo điều kiện thuận lợi cho các quá trình tiếp theo sau được dễ dàng hơn.

==== *HTML* 

Với tên đầy đủ là **H**yper**T**ext **M**arkup **L**anguage (ngôn ngữ đánh dấu siêu văn bản) dùng để cấu trúc nội dung của một trang Web, ví dụ như: chỉ định các đoạn văn bản, tiêu đề, bảng dữ liệu, hoặc nhúng hình ảnh hoặc video vào Web . Mỗi trang web chứa một loạt các liên kết đến các trang khác được gọi là `hyperlinks` (siêu liên kết). Mỗi trang được tạo ra từ nhiều `tag` (thẻ) khác nhau, với cấu trúc một `tag` như sau

.Cấu trúc 1 tag
[source]
....

<tagname> nội dung tag...</tagname>

....

** Các tag thường đi theo cặp, bắt đầu bởi <tagname> và kết thúc bằng </tagname>

IMPORTANT: Tag kết thúc phải có dấu gạch chéo `/` phía trước tên thẻ.

Trang HTML cơ bản có thể được thấy như sau:

[source,html]
----
<!DOCTYPE html>
<html>
<head>
	<title>Page Title</title>
</head>
<body>

	<h1>This is a Heading</h1>
	<p>This is a paragraph.</p>

</body>
</html>
----

Với một số tag cơ bản như sau:

* `<!DOCTYPE html>` cho biết là HTML5
* `<html>` root của trang HTML
* `<head>` chứa thông tin về tài liệu
* `<title>` phần tiêu đề trang
* `<body>` phần chứa nội dung trang hiển thị
* `<h1>` nơi chứa phần tiêu đề chính
* `<p>` phần ghi các đoạn văn bản

==== *JavaScript* 
 
JavaScript là một ngôn ngữ được thiết kế chủ yếu để thêm tương tác vào các trang Web, và tạo ra các ứng dụng Web.

Các chương trình JavaScript có thể được nhúng trực tiếp vào HTML của Web. Và tùy vào mục đích cụ thể, script có thể chạy khi mở trang Web, nhấp chuột, gõ phím, gữi biểu mẫu, cập nhật dữ liệu, giao tiếp với cơ sở dữ liệu,...

Để nhúng chương trình viết bằng JavaScript vào trang HTML, chỉ cần thêm tag `<script>` và thuộc tính `type`. Có thể thêm phần này ở phần `<head>` hoặc phần `<body>` của HTML. Ví dụ sau đây minh họa việc thêm một chương trình JavaScript vào phần thân (<body>) của HTML:

[source,html]
----	
	  <!DOCTYPE html>
	  <html>
	  <head>
	  	<title>My first JavaScript page</title>
	  </head>
	  <body>
        
      	<script type="text/javascript">
     	 // chương trình JavaScript được viết ở đây
     	</script>
		
	  </body>
	  </html>
----


==== *CSS*

**CSS** là từ viết tắt của **C**ascading **S**tyle **S**heets, là một ngôn ngữ được thiết kế để xử lý giao diện Web, giúp các trang Web được đẹp hơn. CSS có thể kiểm soát được màu sắc của văn bản, phong chữ, kích cỡ chữ, khoảng cách giữa các đoạn văn, hình nền hoặc màu nền, và nhiều hiệu ứng khác nửa.

Ví dụ : sử dụng phương thức Encoding UTF-8 ở phần `<head>` trong trang HTML

[source,html]
----	
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title> Sử dụng phương thức Encoding UTF-8</title>
</head>
<body>

</body>
</html>
----

=== Ứng dụng điều khiển đèn LED thông qua Webserver

ESP8266 hoàn toàn có thể thực hiện vai trò Web Server để phục vụ cho một vài kết nối đến, tận dụng giao diện Web để điều khiển, cấu hình cho nó.

Ứng dụng này sẽ sử dụng giao diện Web phục vụ bởi ESP8266 và điều khiển chính đèn LED trên board.

=== Code

[source, c]
----
include::code/WebServer/WebServer.ino[]
----
