[[web-server]]
== Web Server

=== What is Web Server?

When there is a request from a Web Client (e.g. Web Browser), a Web Server will respond and analyse it based on the information it recevies. Web Servers process mostly HTML, JavaScript, CSS, JSON, and other binary data.

Web Servers usually process requests on Port 80, and Port 443 for websites with `HTTPS`.

=== HTML - Javascript - CSS

HTML, Javascript, and CSS are a triad of cornerstone technologies for web development. Some basic knowledge about these would be a benefit for the upcoming chapters.

==== HTML

An acronym for *Hyper Text Markup Language*, HTML is used for document structuring, defining title, tables, or embedding images and other objects into a web page. Each webpage has various links to other webpages called `hyperlinks`. Each page is made of different `tags`, with each tag defined as follows

.A tag structure
[source]
....

<tagname> nội dung tag...</tagname>

....
** Tags come in pair, starting with <tagname> and ending with </tagname>

IMPORTANT: Ending tag must have a forward slash `/` in front of its name.

A simple HTML page is arranged as follows:

[source,html]
----
<!DOCTYPE html>
<html>
<head>
	<title>Page Title</title>
</head>
<body>

	<h1>This is a Heading</h1>
	<p>This is a paragraph.</p>

</body>
</html>
----

Some basic tags:

* `<!DOCTYPE html>` defines the page as HTML5.
* `<html>` root of a HTML page.
* `<head>` contains metadata.
* `<title>` title of the page.
* `<body>` the content that will be presented.
* `<h1>` header type 1.
* `<p>` paragraph.

==== Javascript

Javascript is a language designed to make a website interactive, and for Web application (Web App)

JavaScript application can be embedded directly into a web's HTML. Depending on particular purposes, script can run when accessing a webpage, clicking, typing, sendind forms, updating data, communicating with database.

To embed a Javascript program into a HTML page, a `<script>` is added withh `type` element. This can be done inside `<head>` or `<body>` of the HTML content. Below is an example on how to implement Javascript inside the <body>:

[source,html]
----
<!DOCTYPE html>
<html>
<head>
	<title>My first JavaScript page</title>
</head>
<body>


  <script type="text/javascript">
    // Javascript code is written here
    // before </body>
  </script>
</body>
</html>
----


==== CSS

CSS stands for *Cascading Style Sheets*, a language for web layout design, which is used to enhance a webpage's presentation. CSS can control the colour, font, size, spacing, and background, etc. of a web document.

A example CSS snippet with 4 parts:

[source, css]
----
selector {
   property-a: value-x;
   property-b: value-y;
   .....
}
----

A CSS implementation in HTML

[source, html]
----
<!DOCTYPE html>
<html>
<head>
  <title>My first JavaScript page</title>
  <style>
    .class-select {
      background-color: red;
    }

    #id-select {
      background-color: green;
    }

    div {
      color: blue;
    }
  </style>
</head>
<body>
  <div id="id-select"> css select by id </div>
  <div class="class-select"> css select by class </div>
</body>
</html>
----

With the above HTML document, tag div with id = `id-select` will have a green background, tag div with class = `class-select` will have a red background, and all div tag will have a green font.

=== Controlling a LED using WebServer

ESP8266 can act as a Web Server to process any request, which can be controlled and configured.


=== ESP8266 Web Server

With this application, ESP will initiate a Web Server. When there is a client establishing a connection, ESP8266 will send back a HTML with options for the client to toggle LEDs on the board.

[source, c]
----
include::code-{lang}/WebServer/WebServer.ino[]
----

Proceed after checking the source code:

- <<select-arduino-board>>
- <<arduino-flash>>

=== Combining WiFi API and Web Server
