== Data exchange between 2 ESP8266

Usually, communication between two ESP8266 or more requires existing router or access point, these modules then connect to a single access point and start talking to each other.

Some applications requires no Access Point when connecting 2 ESP8266 together. We can configure one board to act as an Access Point which then creates a TCP Server. Another will act as a usual WiFi Client which then connects to the previously created WiFi, and then initialise a TCP Client to connect to the TCP Server.

=== Requirements

- No router or access point is needed, Communication between two ESP8266 is done in a WiFi network, they will exchange data every second, and then print on the Serial Terminal

=== Procedure

Requirements for 2 ESP8266 in operation:

* A ESP8266 will start _SoftAP_ to create a WiFi network, then initialise a TCP Port for a Server.
* Another ESP8266 acts as a client in _WiFi Station_ mode and connects to the ESP8266 server above.
* Per second, the two will communicate with each other, the one that receive data with print out to the Serial port and send an acknowledgement.

=== Code

.P2P server
[source, c]
----
include::code-{lang}/WiFiP2P/p2p-server.ino[]
----

.P2P client
[source, c]
----
include::code-{lang}/WiFiP2P/p2p-client.ino[]
----

Proceed after checking the source code:

- <<select-arduino-board>>
- <<arduino-flash>>
