== Trao đổi dữ liệu giữa 2 ESP8266

Thông thường, muốn hai hay nhiều ESP8266 có thể liên lạc, trao đổi dữ liệu với nhau sẽ cần đến một router hay access-point, các module ESP8266 này sẽ kết nối vào Access Point rồi sau đó giao tiếp với nhau.

Có một số ứng dụng đơn giản để kết nối 2 ESP8266 với nhau mà không cần Access Point, chúng ta có thể khởi tạo 1 board hoạt động như là  WiFi Access Point, đồng thời khởi tạo 1 TCP Server. Board khác hoạt động như 1 WiFi client thông thường, kết nối vào mạng WiFi đã được tạo, và khởi động 1 TCP Client kết nối vào TCP Server kia.

=== Yêu cầu

- Không cần bất kỳ một Router, hay Access Point nào, thực hiện việc kết nối giao tiếp giữa 2 ESP8266 thông qua mạng WiFi, 2 Board này sẽ truyền dữ liệu với nhau mỗi giây, và hiển thị lên Serial Terminal

=== Hướng dẫn thực hiện

Để trao đổi dữ liệu giữa 2 ESP8266 cần đáp ứng các điều kiện sau:

* 1 ESP8266 sẽ khởi động _SoftAP_ để tạo mạng WiFi, đồng thời khởi động 1 TCP Server để làm Server
* 1 ESP8266 phải là client với chế độ _WiFi Station_ và kết nối đến ESP8266 server trên
* Sau mỗi giây, Board ESP8266 này sẽ gởi dữ liệu vào Board kia, board nhận được dữ liệu sẽ in ra cổng Serial và gởi ngược lại.

=== Code

.P2P server
[source, c]
----
include::code/WiFiP2P/p2p-server.ino[]
----

.P2P client
[source, c]
----
include::code/WiFiP2P/p2p-client.ino[]
----
