[abstract]
== Giới thiệu nội dung

Nội dung quyển sách này bao gồm các hướng dẫn chi tiết cho người đọc lập trình ứng dụng IoT sử dụng Chip WiFi phổ biến hiện này là ESP8266 để kết nối với Server, gởi, nhận gởi dữ liệu và thực thi các lệnh từ Server. Internet Of Things dựa và các kết nối Internet khá nhiều, do vậy các nội dung cũng tập trung nhiều vào các giao thức (prototcol), các phương pháp quản lý cũng như cấu hình kết nối.

Phần cứng sử dụng chính là System On Chip (SoC) **ESP8266** - có khả năng kết nối WiFi và lập trình được với giá thành rẻ và phổ biến trên thế giới. Board mạch sử dụng là board phần cứng mở https://github.com/iotmakervn/iot-wifi-uno-hw[IoT WiFi Uno] có sơ đồ chân tương thích với các board Arduino Uno.

Phần mềm sử dụng lập trên máy tính cho Chip ESP8266 là https://arduino.cc[*Arduino*], ngôn ngữ lập trình `C/C++`

Các phần liên quan đến Server chạy trên máy tính sử dụng https://nodejs.org[NodeJS] với ngôn ngữ lập trình `Javascript`

Ngoài ra, bạn sẽ cần tìm hiểu một số công cụ và khái niệm thường xuyên được sử dụng trong quyển sách này như sau:

* **Git** Trình quản lý phiên bản sử dụng rất rộng rãi trên thế giới, **Github** là một mạng xã hội cho lập trình viên dựa trên Git. Git giúp bạn quản lý được mã nguồn, làm việc nhóm, xử lý các thao tác hợp nhất, lịch sử mã nguồn ... Có thể trong quá trình làm việc với quyển sách này, bạn sẽ cần sử dụng các thư viện mã nguồn mở cho Arduino từ Github, nên việc cài đặt và sử dụng công cụ khá cần thiết cho việc đó. Chưa kể, nó sẽ giúp bạn quản lý mã nguồn và dự án ngày càng chuyên nghiệp hơn.
* **Sublime Text** là một trình soạn thảo phổ biến, nhanh, nhẹ và nhiều tính năng hay. Sử dụng để lập trình Javascript (NodeJS)
* Code formater, dùng để định dạng mã nguồn phù hợp, dễ đọc, dễ sửa chữa
* Editorconfig, là một công cụ cộng thêm cho các Editor, giúp việc đồng bộ hóa các tiêu chuẩn như Indent, Align, Space ... để đảm bảo code khi được mở ở các Editor không bị thay đổi.


NOTE: Tuy phần cứng chính thức sử dụng là board mạch phần cứng mở https://github.com/iotmakervn/iot-wifi-uno-hw[IoT WiFi Uno], nhưng bạn hoàn toàn có thể sử dụng bất kỳ board ESP8266 nào khác trên thị trường cho cuốn sách này, ví dụ như: `NODEMCU`, `Wemos`, ...

TIP: Các nội dung trong quyển sách này tập trung vào hướng dẫn các giao thức, cách thức làm việc với có hệ thống với board ESP8266, Server ..., còn các dự án mẫu, hướng dẫn chi tiết có thể tìm thêm tại **https://arduino.esp8266.vn**

TIP: Tất cả các phần Code đều không giải thích rõ chi tiết API cho mỗi tính năng. Mà thay vào đó được cung cấp tại phụ lục Cheat Sheet (Arduino và C)

=== Ai có thể sử dụng?

- Các lập trình viên phần mềm/Mobile App, Web App… muốn tham gia làm sản phẩm `IoT`
- Sinh viên muốn nâng cao kỹ năng, bổ sung kiến thức
- Cá nhân muốn tự mình làm các sản phẩm phục vụ cuộc sống, phục vụ công việc
- Startup Tech không chuyên về phần cứng hoặc phần mềm

=== Mục tiêu mang lại cho người đọc

- Giúp cho người không chuyên về phần cứng tiếp cận để làm sản phẩm IoT dễ dàng
- Có thể tự phát triển hệ thống tích hợp cho sản phẩm IoT
- Hiểu biết về quy trình tạo ra sản phẩm phần cứng, đi vào mảng sản xuất thiết bị
- Tránh những sai sót không đáng có khi phát triển và thiết kế sai hệ thống

=== Chuẩn bị

- Ít nhất bạn cần 1 board mạch ESP8266 lập trình được, tốt nhất nên sử dụng các board mạch tương tích với Arduino IDE (đã có các module nạp cho chip)
- Nên có thêm các module khác như cảm biến, động cơ để thực hành, một bộ StarterKit là phù hợp
- 1 máy tính cá nhân (Windows, MacOS hoặc Linux)
- C & Arduino ESP8266 Cheatsheet (Mục lục cuối quyển sách này)
