[abstract]
== Introduction to contents

The contents of this book include detailed instructions for IoT application developers using the popular WiFi chip ESP8266, to connect to the server, send and receive data, and execute commands from the server. Internet Of Things depends on the Internet connection, so the content is also focused on protocols, management methods as well as connection configuration.

The main hardware used is System On Chip (SoC). ** ESP8266 ** - WiFi and programmable with cheap price and popular in the world. The circuit board used is the hardware open. https://github.com/iotmakervn/iot-wifi-uno-hw[IoT WiFi Uno]  has a legacy mapping board compatible with Arduino Uno.

The software used on the computer for the ESP8266 chip is https://arduino.cc[*Arduino*], the `C/C++` programming language.

The parts related to Server running on the computer use https://nodejs.org[NodeJS] and `Javascript` programming.

In addition, you will need to learn some of the tools and concepts that are frequently used in this book:

* **Git** - is a version control system for tracking changes in computer files and coordinating work on those files among multiple people, **Github** is a social network for developer based on Git. Git helps you manage source code, group work, merge operations, source code history ... Probably in the process of working with this book, you will need to use open source libraries for Arduino from Github, so the installation and use of the tool is quite necessary for that. It will help you manage the source code and project more and more professional.

* **Sublime Text** - A popular, fast, lightweight and feature rich editÚe Use for programming. Javascript (NodeJS)
* Code formater - Used to format the source code, easy to read, easy to repair.
* Editorconfig - An additional tool for the Editor, which helps to synchronize standards such as Indent, Align, Space ... to ensure that code is opened in the Editor is not changed.


NOTE: Although the official hardware is hardware open https://github.com/iotmakervn/iot-wifi-uno-hw[IoT WiFi Uno], but you can use any board ESP8266 on the market for this book, eg: `NODEMCU`,` Wemos`, ...

TIP: The content in this book focuses on protocol guidance, how to work with systems using ESP8266, Server ..., and sample projects.

TIP: All Code sections do not explain the API details for each feature. Instead, it is provided in the Appendix Cheat Sheet (Arduino and C).

=== Who can use?

- Software developers / Mobile App, Web App ...the person who wants to participate as `IoT` products.
- Students want to improve their skills and additional knowledge.
- Individuals want to make their own products for life, serving the work.
- Startup Tech does not specialize in hardware or software.

=== Target of this book

- Help for non-hardware approach to make the product easy IoT.
- Can be integrated system development for IoT products.
- Understanding the process of creating hardware products, go into the production of equipment.
- Avoid unnecessary errors when developing and designing the system.

=== Preparation

- You need a programmable ESP8266 board, it is best to use a board that is compatible with the Arduino IDE (which has modules for the chip).
- There should be additional modules such as sensors, motors to practice, a set of StarterKit is suitable.
- 1 personal computer (Windows, MacOS or Linux).
- C & Arduino ESP8266 Cheatsheet (Contents at the end of this book).
