[preface]
= Introduction

*Internet Of Things (IoT)* –  *The Internet of Things* seems to be in the forefront of a modern, civilized world. It's a scenario where everything can be connected via the wireless Internet. Businesses are increasingly adopting IoT technology into production because of the potential market for innovation and lower production costs.

Seeing the fast-paced development of IoT technology products and the potential start-up technology market, this book provides IoT content with a coherence, fact, towards young people who have been and want to focus their energies on the Internet of Things. Desire to create unique products, creative, increasingly perfect and synchronized to meet the needs of life.

The content is designed essentially to give students an overview of system construction, equipment production and easy access to the IoT.

=== About author
The author of book is a Mr. https://twitter.com/tuanpmt[Phạm Minh Tuấn](https://github.com/tuanpmt[TuanPM]), he has many years of experience working in the IoT and developing the open source library for the community. He wants to share a little of his knowledge to the development very potential this industry.

=== Terminology used
* `IoT` - Internet Of Things.
* `ESP8266` - Wi-Fi microcontroller.
* `Git` - version control system .
* `Github` - A social network for developer based on Git.
* `IDE` -  Integrated Development Enviroment.
* `Compiler` - A software program that transforms high-level source code that is written by a developer in a high-level programming language into a low level object code (binary code) in machine language.
* `Logic Level` - The voltage level for the chip to understand (1 or 0).

=== Explain the source code

[source, c]
----
void setup()
{
    //comment <1>
    int a = 1;
    a ++; <2>
}
----

<1> This line explains this as a comment.
<2> This line explains the variable `a` which adds 1 unit.
