[[_getting_started]]
= Basic knowledge

In this chapter, we start off with an overview of **IoT** system, **ESP8266** product line, and then how to set up a **Arduino** working environment on your computer. Next we proceed to some sample programs, which library to use. After this chapter, you will have a general view on an IoT system, and grapse how to use the tools necessary for prgramming ESP8266

A quick look at the chapter:

* `IoT` and pratical applications.
* Get to know `ESP8266` WiFi chip.
* `Arduino IDE` using Arduino with ESP8266.
* `Starter Kit`, an `IoT` starter kit.
* `Node.js - Javascript`, server-side programming language.
* `Installing` all necessary tools.

Those who are familiar with ESP8266, have worked with an IoT system, or are proficient in **C/C++** programming can skip this part.


include::01-iot.{lang}.adoc[]

include::02-esp8266.{lang}.adoc[]

include::03-arduino.{lang}.adoc[]

include::04-nodejs.{lang}.adoc[]

include::05-prepare.{lang}.adoc[]

== Summary

At this point, you have a basic understanding of the ecosystem, the tools and procedures working with ESP8266 as well as an **IoT** system. In addition, you can now start developing an ESP8266-based application. All the selected tools work on multiple platforms such as Mac OS, Windows, or Linux.