[[_fota]]
= Firmware update over the air (FOTA)

Among nowadays software development and products development processes, partially periodically public the result bring the most effective, products will earlier derive to end user, earlier get user's feedback, and more reasonable customized. The early public make products poor of features and need to update, and enrich products' quality in the future.

Applications update over the air on mobile phone and PC is already popular. Software applications are updated weekly, monthly... to fix issues, upgrade features.

It is similar with hardware products, features should be updated over the air since the development phase. Beside the easy to update features in the future, issues fixing, system upgrade over the air will save a lot of costs and resources.

In this article, we will study methods to update over the air for ESP8266, how to wireless flash the firmware for module, how ESP8266 can automatically download the firmware, how ESP8266 can automatically boots up an HTTP server to get the web interface then upload firmware onto chip.


include::01-fota.{lang}.adoc[]

include::02-arduino-ide.{lang}.adoc[]

include::03-webbrowser.{lang}.adoc[]

include::04-http-server.{lang}.adoc[]
