
[[_DHT11_logger]]
= Temperature and Humidity Monitor using DHT11, ESP8266 and Node.js server

In this project, using DHT11 temperature and humidity sensor, we will build a small circuit to monitor the temperature and humidity of the surroundings. That data will be sent back to PC and we can read that data on an Arduino IDE terminal. We can also visit a given URL to view it and its plot on a web interface.
Some background knowledge:

* *The temperature* is a physical quantity expressing the subjective perceptions of `hot and cold`. Temperature is measured with a thermometer, historically calibrated in various temperature scales and units of measurement. The most commonly used scales are the Celsius scale, denoted in °C (informally, degrees centigrade), the Fahrenheit scale (°F), and the Kelvin scale. The Kelvin (K) is the unit of temperature in the International System of Units (SI), in which temperature is one of the seven fundamental base units. In Vietnam and most of the world, the Celsius scale is used for most temperature measuring purposes. We are using °C in this project.

* *The relative humidity* is the ratio of the partial pressure of water vapor to the equilibrium vapor pressure of water at a given temperature. Relative humidity is normally expressed as a percentage; a higher percentage means that the air–water mixture is more humid.

* *The DHT11* is a basic and low-cost digital temperature and humidity sensor. It's fairly simple to use and we can grab its data with 1-WIRE Protocol.


include::01-design.{lang}.adoc[]

include::02-server.{lang}.adoc[]

include::03-esp8266.{lang}.adoc[]

include::04-extend.{lang}.adoc[]

== Summary

Upon completion of this project, you will have an overview of building a complete sensors data logging project as well as building a web server to serve the clients from scratch. This will help you lay the foundations for many larger data logging and analyzing projects in the future.
