
[[_DHT11_logger]]
= Dự án đọc cảm biến DHT11 và gởi về Server

Trong bài này chúng ta sẽ xây dựng ứng dụng dùng cảm biến DHT11 để thu thập nhiệt độ, độ ẩm của môi trường. Thông tin về nhiệt độ và độ ẩm sẽ được
hiển thị trên máy tính và hiển thị trên trình duyệt web bằng cách truy cập vào 1 địa chỉ URL được chỉ định. Một số kiến thức cần thiết :

* *Nhiệt độ* là đại lượng thể hiện tính chất vật lý `nóng, lạnh` của vật chất. Nhiệt độ được đo bằng các đơn vị khác nhau và có thể biến đổi bằng
các công thức. Trong hệ đo lường quốc tế, nhiệt độ được đo bằng đơn vị Kelvin, ký hiệu là K. Trong đời sống ở Việt Nam và nhiều nước, nó được đo bằng
độ C.

* *Độ ẩm tương đối* là tỷ số của áp suất hơi nước hiện tại của bất kỳ một hỗn hợp khí nào với hơi nước so với áp suất hơi nước bão hòa tính theo đơn
vị là %. Định nghĩa khác của độ ẩm tương đối là tỷ số giữa khối lượng nước trên một thể tích hiện tại so với khối lượng nước trên cùng thể tích đó khi
hơi nước bão hòa

* *DHT11* là một cảm biến có khả năng đo nhiệt độ và độ ẩm không khí với độ chính xác vừa phải, giá cả phải chăng. Có thể lấy dữ liệu
đo được của cảm biến bằng giao thức OneWire.


include::01-design.adoc[]

include::02-server.adoc[]

include::03-esp8266.adoc[]

include::04-extend.adoc[]
