== Thiết kế ứng dụng

Đây là một ứng dụng khá đơn giản, hữu ích và dễ làm. Thông qua phần này chúng ta có thể xây dựng được một ứng dụng *IoT* thực tế, nắm bắt được các kiến thức cơ bản về thu thập dữ liệu, xây dựng thiết bị và server.

=== Yêu cầu

- Thiết bị sẽ đo nhiệt độ, độ ẩm dùng cảm biến DHT11, đấu nối với board mạch ESP8266
- Board mạch kết nối không dây đến mạng WiFi và gởi dữ liệu về HTTP Server
- Phần cơ bản: HTTP Server hiển thị dữ liệu nhiệt độ, độ ẩm ra màn hình Log
- Phần nâng cao: HTTP Server lưu trữ dữ liệu, và cung cấp file HTML cho người dùng có thể xem qua Browser

=== Phân tích

- Chúng ta cần 1 Web Server viết bằng Javascript, thực thi bởi Node.js, lắng nghe ở Port 80 trên máy tính cá nhân.
- Máy tính có kết nối cùng mạng WiFi nội bộ với ESP8266, và biết rõ địa chỉ IP của máy tính, ví dụ `192.168.1.102`
- ESP8266 sau khi kết nối vào mạng WiFi nội bộ, sẽ tiến hành đọc thông số nhiệt độ, độ ẩm từ cảm biến DHT11 và gởi về Server sau mỗi 5 giây.
- Quá trình gởi được thực hiện bởi phương thức `GET`, ví dụ `http://192.168.1.102/update?temp=25&humd=80` với `192.168.1.102` là địa chỉ Web Server, `/update` là đường dẫn, `temp=20` và `humd=80` chứa thông tin nhiệt độ 20 độ C và độ ẩm 80%.
- Web Server trả về trạng thái HTTP status = 200 (OK), cùng với việc hiển thị ra cửa sổ log giá trị nhiệt độ, độ ẩm.
- Ở phần nâng cao:
  -- Web Server lưu trữ dữ liệu nhiệt độ, độ ẩm trong mảng, chứa ở bộ nhớ RAM
  -- Web Server còn cung cấp 1 file `index.html` chứa mã Javascript có thể yêu cầu lấy dữ liệu nhiệt độ, độ ẩm lưu trong RAM, và hiển thị lên biểu đồ

