== Server Nodejs

Về phía Web Server, chúng ta cần đảm bảo nó có thể phục vụ cho nhiều Client, với `path` là:
- `/update` thì sẽ thêm mới dữ liệu để lưu trữ, và in ra màn hình
- `/get` trả về dữ liệu đã lưu trữ định dạng JSON
- `/\*` Còn lại thì trả về file `index.html`
- Mảng dữ liệu lưu trữ có định dạng: `[{"temp": 25, "humd":80, time: "time"}, ...]`

[source, javascript]
----
include::code/server.js[]
----
<<<<<<< HEAD
// o esp8266 chi can gui len server 2 gia tri nhiet do va do am.
// tạo mang null arr[] de luu temp, humi. Su dung arr.push() de lay du lieu cua mang. Khi khach hang truy cap vao localhosst:port/ thi
// tra ve file index (neu web browser yeu cau). Truong hop truy cap vao localhosst:port/update? => tra ve gia tri theo
// ding dang chuoi json
//-------------------------------------------
// git gutter de cap nhat noi dung thay doi.
//-------------------------------------------
// ve chart dung javascript, dung code canvas
//-------------------------------------------
// su dung xhtml dung get gia tri
//-------------------------------------------
=======

Bạn có thể thực thi đoạn code trên với dòng lệnh `node server.js`, thử truy vập vào http://localhost:8000 để xem trang `index.html`. Hoặc truy cập vào http://localhost:8000/update?temp=20&humd=60 để xem màn hình Log in ra kết quả nhiệt độ và độ ẩm.

----
{ temp: '30', humd: '80', time: 2017-08-21T16:56:23.358Z }
{ temp: '31', humd: '80', time: 2017-08-21T16:57:06.277Z }
{ temp: '36', humd: '80', time: 2017-08-21T16:57:17.708Z }
----

Tạm thời ở phần cơ bản chúng ta chưa cần phải quan tâm đến file `index.html` và đoạn code Javascript trong đó. Cũng nhưng chưa quan tâm tới việc xử lý khi đường dẫn là `/get` hoặc `/\*`, mà chỉ quan tâm duy nhất khi nhận được với đường dẫn `/update`.

Một ứng dụng khá phổ biến là bạn muốn hiển thị các dữ liệu thu thập được ở trình duyệt Web. Vậy chúng ta sẽ làm 1 file `index.html` chứa mã nguồn Javascript có thể yêu cầu Server trả về dữ liệu mỗi giây để hiển thị lên 1 biểu đồ canvas.

[source, html]
----
include::code/index.html[]
----
>>>>>>> 9b0d5e5b1c7f8e4d2b943062941f4e5d11ddb8bf
