== Server Nodejs

Về phía Web Server, chúng ta cần đảm bảo nó có thể phục vụ cho nhiều Client, với `path` là:

* `/update` thì sẽ thêm mới dữ liệu để lưu trữ, và in ra màn hình

* `/get` trả về dữ liệu đã lưu trữ định dạng JSON

* `/\*` Còn lại thì trả về file `index.html`

* Mảng dữ liệu lưu trữ có định dạng: `[{"temp": 25, "humd":80, time: "time"}, ...]`

**Mã nguồn file `server.js`**
[source, javascript]
----
include::code/server.js[]
----

**Giải thích mã nguồn**

require dùng để load các thư viện hoặc module cần thiết cho dự án

----
var fs = require('fs');     // module giúp đọc file từ server hoặc upload file lên server
var url = require('url');   // chia nhỏ URL thành những thành phần để dễ dàng truy xuất
var http = require('http');
var querystring = require('querystring');// module giúp chuyển string sang object
var db = []; // khai báo 1 biến kiểu mảng
----

Hàm requestHandler() giúp gửi (response) hoặc nhận yêu cầu (request) đến client

----
// Giả sử địa chỉ nhận được http://192.168.1.7:8000/update?temp=30&humd=40
var uriData = url.parse(request.url);
var pathname = uriData.pathname;          // /update
var query = uriData.query;                // temp=30.5&hum=40
var queryData = querystring.parse(query); // queryData.temp = 30
                                          // queryData.humd = 40
----

So sánh giá trị pathname để xử lí dữ liệu

----
// Biến newData sẽ lấy dữ liệu client gửi lên thông qua URL,sau đó đẩy dữ liệu vào mảng db
if(pathname == '/update') {
  var newData = {
      temp: queryData.temp,
      humd: queryData.humd,
      time: new Date()        //Lấy thời gian hiện tại
  }
  db.push(newData);
  console.log(newData);     // Hiển thị ra Log giá trị nhận được từ client (ESP8266)
----

Trả về định dạng JSON của mảng db nếu pathname = /get, sau đó xóa giá trị của mảng

----
else if(pathname == '/get') {
  response.writeHead(200, { 'Content-Type': 'application/json' }); //khai báo định dạng trả về là JSON, HTTP status code =200
  response.end(JSON.stringify(db));     // chuyển nội dung từ mảng db sang định dạng JSON
  db = [];
}
----

Trả về nội dung của file index.html khi không xảy ra 2 trường hợp trên

----
else{
// Dùng fs để đọc file index.html và gán nội dung vào content
  fs.readFile('./index.html', function(error, content) {
      response.writeHead(200, {'Content-Type': 'text/html' });// khai báo định dạng trả về là html để đọc file
      response.end(content);
  });
----

Khởi tạo một server HTTP và mở port 8000 để client truy cập

----
var server = http.createServer(requestHandler);
server.listen(8000);
----

Bạn có thể truy cập đến đường dẫn của file server.js và thực thi đoạn code trên với dòng lệnh `node server.js`, sau đó thử truy vập vào http://localhost:8000 để xem trang `index.html`. Hoặc truy cập vào http://localhost:8000/update?temp=20&humd=60 để xem màn hình Log in ra kết quả nhiệt độ và độ ẩm.

----
{ temp: '20', humd: '60', time: 2017-08-21T16:56:23.358Z }
{ temp: '20', humd: '60', time: 2017-08-21T16:57:06.277Z }
{ temp: '20', humd: '60', time: 2017-08-21T16:57:17.708Z }
----

Ở phần cơ bản chúng ta chưa cần phải quan tâm đến file `index.html` và đoạn code Javascript trong đó. Cũng nhưng chưa quan tâm tới việc xử lý khi đường dẫn là `/get` hoặc `/\*`, mà chỉ quan tâm duy nhất khi nhận được với đường dẫn `/update`.

Khi đã hoàn thành phần cơ bản chúng ta sẽ đi đến một ứng dụng khá phổ biến, người dùng cần hiển thị các dữ liệu thu thập một cách trực quan thông qua trình duyệt Web. Vì vậy chúng ta sẽ làm 1 file `index.html` chứa mã nguồn Javascript có thể yêu cầu Server trả về dữ liệu mỗi giây để hiển thị lên 1 biểu đồ canvas.

**Mã nguồn file `index.html`**
[source, html]
----
include::code/index.html[]
----

**Giải thích mã nguồn**

Khởi tạọ trang HTML và các thuộc tính liên quan

----
<!DOCTYPE html>           <!-- !DOCTYPE: cho trình duyệt biết phiên bản HTML được sử dụng -->
<html>                    <!-- tag <html> cho trình duyệt biết đây là văn bản HTML.-->
<head>                    <!-- Tag <head> khai báo thông tin cho trang HTML -->
<meta charset="UTF-8">    <!-- Tag <meta /> cung cấp dữ liệu về văn bản HTML, dạng mã hóa charset="UTF-8" -->
<title>DHT11</title>      <!-- Tiêu đề của trang -->
</head>
----

Tạo các textbox để chứa nội dung hiển thị trong phần body của trang HTML

----
<body>      <!-- Tag <body> định nghĩa phần thân của văn bản HTML. -->
            <!-- Tạo 2 textbox trong tag tiêu đề phụ <h1> -->
  <h1> Temprature</h1> <input type="text" size="6" id="temp">&#176;C
  <br>
  <h1> Humidity</h1> <input type="text" size="6" id="humd">%
----

Phần còn lại sử dụng các thuộc tính của thư viện HTML5 Canvas JavaScript để có thể vẽ đồ thị nhiệt độ, độ ẩm
