[_contributors]]
= The ending

=== Contributors.

To complete the content of the book also contributed by the following members:

- 1. https://twitter.com/tuanpmt[*Phinh Minh Tuan (TuanPM)*]
- 2. https://github.com/lamnhatquan[*Lâm Nhật Quân*]
- 3. https://github.com/trinhduc[*Viet Hoang Duc *]
- 4. *Lê Phương Trình* - Internship at IoT Maker Vietnam - Ho Chi Minh City University of Technology University students, specialization in telecommunications electronics, course 2014.
- 5. Tran Phuc Vinh - Internship at IoT Maker Vietnam - Ho Chi Minh City University of Technology University students, majors in electrical engineering, course 2014.

Translated to English:


And use the community contributions at https://arduino.esp8266.vn

=== Thank you

Glad you went with us to the end of this book. The purpose of the book is to help beginners learn about `Internet Of Things (IoT)` with the basic knowledge and precise effectioncy to study IoT more quickly. Hope the book will come to hand many of you are passionate about the new but very potential technology. Wish you success on the road that you have chosen.

Although tried to finish the best content for the book, however, inevitably the shortcomings. Any suggestions for opening issues at: https://github.com/tuanpmt/iot-for-beginners-book

Some websites contribute to the community (wish to receive your contribution and contribution to the community of IoT Vietnam in particular as well as the technical community is developing more):

- 1. About ESP8266 with Arduino: https://arduino.esp8266.vn/
- 2. About ESP32: https://esp32.vn

=== License to use documents.

image::contributions/Cc-by-nc-sa_icon.svg[width="200", role="center", align="center"]
