WebSokets is an advanced technology that support two-ways communication between client and server by using TCP socket to create a  continuous, effective, and low cost connection. Although, it is built for web applications, developers might using it for any kind of projects.

WebSockets is newly introduced in HTML5, allowing bidirectional parallel communications and supported by most of web browsers. Communication is opened via an HTTP request, including special headers that notice Server (supported) switch to WebSocket connection. This connection is maintained then you can send and receive data continuously, no interruption, without any other HTTP header needed.

WebSockets supports most popular web browsers such as: Google Chrome, Microsoft Edge, Internet Explorer, Firefox, Safari and Opera.

=== Advantages

WebSockets provides the ability on bidirectional connections which is continuously maintained, low latency, easy to communicate between Client and Server. That is why WebSockets is proper for real-time applications, end user do not need to reload their browser to update data like HTTP protocol.

=== Disadvantages

WebSockets protocol has not been supported by all web browsers already. WebSockets also require to supported by web applications on server.
